### ISSUE TITLE
bundle install fails to install extpp gem on Mac Catalina

### ISSUE THREAD

**Issue by SathishAchilles** [red-data-tools/extpp#9] opened 2020-08-31 15:20 UTC
bundle install fails to install extpp gem on Mac Catalina, below are the error details..
```
Fetching extpp 0.0.8
Installing extpp 0.0.8 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/gems/extpp-0.0.8/ext/extpp
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r
./siteconf20200831-4129-ade1ei.rb extconf.rb
checking --enable-debug-build option... no
checking C++ compiler... xcrun clang++

current directory: /.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/gems/extpp-0.0.8/ext/extpp
make "DESTDIR=" clean
rm -rf /.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/gems/extpp-0.0.8/ext/extpp/protect.o
/.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/gems/extpp-0.0.8/ext/extpp/object.o
/.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/gems/extpp-0.0.8/ext/extpp/function.o
/.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/gems/extpp-0.0.8/ext/extpp/class.o libruby-extpp.dylib

current directory: /.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/gems/extpp-0.0.8/ext/extpp
make "DESTDIR="
"xcrun clang++" -I/.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/gems/extpp-0.0.8/include
-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0
-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19
-D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -DRB_EXTPP_COMPILATION  -g -Os -pipe -o
/.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/gems/extpp-0.0.8/ext/extpp/protect.o -c
/.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/gems/extpp-0.0.8/ext/extpp/protect.cpp
/bin/sh: xcrun clang++: command not found
make: *** [/.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/gems/extpp-0.0.8/ext/extpp/protect.o] Error 127

make failed, exit code 2

Gem files will remain installed in /.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/gems/extpp-0.0.8 for inspection.
Results logged to /.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/extensions/universal-darwin-19/2.6.0/extpp-0.0.8/gem_make.out

An error occurred while installing extpp (0.0.8), and Bundler cannot continue.
Make sure that `gem install extpp -v '0.0.8'` succeeds before bundling.
```
I do have xclang ++ installed
```
which clang++                                                                                                                                     
=> /usr/bin/clang++
```

```
xcrun -find clang++        
=> /Library/Developer/CommandLineTools/usr/bin/clang++
```

`/.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/extensions/universal-darwin-19/2.6.0/extpp-0.0.8/mkmf.log` mkmf log file shows below log..
```
check_debug_build: checking --enable-debug-build option... -------------------- no

--------------------

check_cxx: checking C++ compiler... -------------------- xcrun clang++

--------------------
```

ruby version - `2.5.8`

extpp gem version - `0.0.8`

`gem install extpp -v '0.0.8'` works, but bundle install fails always with the same above mentioned error

**Comment by kou** [comment] 2020-09-01 01:33
```diff
diff --git a/ext/extpp/extconf.rb b/ext/extpp/extconf.rb
index 9781203..77fafcd 100644
--- a/ext/extpp/extconf.rb
+++ b/ext/extpp/extconf.rb
@@ -53,7 +53,7 @@ HEADERS = #{headers.collect(&:quote).join(" ")}
 
 INCLUDE_DIR = #{include_dir.quote}
 
-CXX = #{RbConfig::CONFIG["CXX"].quote}
+CXX = #{RbConfig::CONFIG["CXX"]}
 
 RUBY = #{RbConfig.ruby.quote}
 RUBY_HEADER_DIR = #{RbConfig::CONFIG["rubyhdrdir"].quote}
```

will solve but it may cause other problem when users want to use `/path/include space/bin/clang++`.

We need to find more robust solution.

**Comment by SathishAchilles** [comment] 2020-09-01 05:43
@kou is there a workaround for now by passing additional flags to bundle install ?

**Comment by kou** [comment] 2020-09-01 05:46
Why do your `RbConfig::CONFIG["CXX"]` return `xcrun clang++` not `clang++`?

**Comment by SathishAchilles** [comment] 2020-09-01 05:51
@kou ehh I don't think so, I tried the same via an IRB session from the same environment, I get the below..
```
irb(main):001:0> RbConfig::CONFIG["CXX"]
=> "clang++"
```

**Comment by kou** [comment] 2020-09-01 06:08
What is returned by `RbConfig.expand("$(CXX)")`?

**Comment by kou** [comment] 2020-09-01 06:12
Is Ruby 2.6 used?

```text
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20200831-4129-ade1ei.rb extconf.rb
```

**Comment by SathishAchilles** [comment] 2020-09-01 06:28
> RbConfig.expand("$(CXX)")
```                                                                                                                                     ─╯
irb(main):001:0> RbConfig.expand("$(CXX)")
=> "clang++"
```

**Comment by SathishAchilles** [comment] 2020-09-01 06:30
> Is Ruby 2.6 used?
> 
> ```
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20200831-4129-ade1ei.rb extconf.rb
> ```

```/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20200831-4129-ade1ei.rb extconf.rb
Traceback (most recent call last):
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby: No such file or directory -- extconf.rb (LoadError)
```

**Comment by kou** [comment] 2020-09-01 06:35
The command line exists in your log.
Why does the log exist in your log?

**Comment by kou** [comment] 2020-09-01 06:37
Ah, system Ruby uses `xcrun clang++`:

```console
$ /usr/bin/ruby -e 'p RbConfig.expand("$(CXX)")'
"xcrun clang++"
```

**Comment by kou** [comment] 2020-09-01 06:38
It seems that you use system Ruby not Ruby installed by rbenv.

**Comment by SathishAchilles** [comment] 2020-09-01 06:39
Yeah could see that too 
```
/usr/bin/ruby -e 'p RbConfig.expand("$(CXX)")'                       ─╯
"xcrun clang++"
```
my system ruby is `ruby 2.6.3p62`

**Comment by SathishAchilles** [comment] 2020-09-01 06:40
> It seems that you use system Ruby not Ruby installed by rbenv.

no as you see in the logs, I am using ruby `2.5.8` installed via `rbenv`..

**Comment by kou** [comment] 2020-09-01 06:46
Why does your log include `/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20200831-4129-ade1ei.rb extconf.rb`?

**Comment by SathishAchilles** [comment] 2020-09-01 06:49
@kou I know why the logs had that.. for some reason `bundle install`  actually refers to `system ruby` even though it is run after setting local version using rbenv.. now when I tried to install using the bundle executable of the local repo `bin/bundle`  the installation went fine..

**Comment by kou** [comment] 2020-09-01 10:00
Can we close this?

**Comment by SathishAchilles** [comment] 2020-09-01 10:41
so any idea why this actually happens with `system ruby`?

**Comment by kou** [comment] 2020-09-01 10:50
> this

Does this refer "`bundle install` uses system Ruby not rbenv Ruby"?

**Comment by SathishAchilles** [comment] 2020-09-01 11:06
@kou  actually `bundle env` shows that bundle is running against system ruby.. I guess that's the reason .. 
## Environment

```
Bundler       2.1.4
  Platforms   ruby, universal-darwin-19
Ruby          2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
  Full Path   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  Config Dir  /Library/Ruby/Site
RubyGems      3.0.3
  Gem Home    /Users/sathish/.rbenv/versions/2.5.8/gemsets/bug-fix-extpp
  Gem Path    /Users/sathish/.rbenv/versions/2.5.8/gemsets/bug-fix-extpp:/Users/sathish/.rbenv/versions/2.5.8/gemsets/global:/Users/sathish/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0
  User Home   /Users/sathish
  User Path   /Users/sathish/.gem/ruby/2.6.0
  Bin Dir     /Users/sathish/.rbenv/versions/2.5.8/gemsets/bug-fix-extpp/bin
Tools
  Git         2.27.0
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed

**Comment by SathishAchilles** [comment] 2020-09-01 11:39
if possible, I would like to understand why it fails only for system specific ruby that is why is `CCX` flag is not as expected, is the `Rbconfig` set to this value for any specific purpose?

**Comment by kou** [comment] 2020-09-01 22:04
Do you want to know why `RbConfig.expand("$(CXX)")` on system Ruby returns `"xcrun clang++"`, right?
I don't know why but it will be caused by building Ruby with `CC="xcrun clang" CXX="xcrun clang++"` environment variables.

**Closed as completed by kou** 2020-09-01 22:04 UTC
